name: Quality Gate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: prefeitura-rio/actions/quality-gate@master
        with:
          check: app:format

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: prefeitura-rio/actions/quality-gate@master
        with:
          check: app:lint

  strlint:
    name: Structural Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: prefeitura-rio/actions/quality-gate@master
        with:
          check: app:strlint

  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: prefeitura-rio/actions/quality-gate@master
        with:
          check: app:typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [format, lint, strlint, typecheck]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: prefeitura-rio/actions/quality-gate@master
        with:
          check: app:test
